CREATE DATABASE IF NOT EXISTS reseachspace;
USE reseachspace;

CREATE TABLE IF NOT EXISTS users (
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(150) UNIQUE NOT NULL,
 password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS papers (
 id INT AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(255) NOT NULL,
 abstract TEXT NOT NULL,
 topic VARCHAR(100) NOT NULL,
 year INT NOT NULL,
 author_id INT NOT NULL,
 file_name VARCHAR(255) NOT NULL,
 file_path VARCHAR(255) NOT NULL,
 views INT DEFAULT 0,
 downloads INT DEFAULT 0,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (author_id) REFERENCES users(id)
);
